steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/base:latest'
      - .
      - '-f'
      - Dockerfile
    id: Build
    timeout: 800s
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/base:latest'
    id: Push
    timeout: 800s



images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/base:latest'
options:
  substitutionOption: ALLOW_LOOSE
  diskSizeGb: '10'
substitutions:
  _GCR_HOSTNAME: us.gcr.io
timeout: 800s