version: '3.7'

services:

  main:
    build: .
    container_name: test_main
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:/usr/src/app
    networks:
      main:

networks:
  main:
    name: database_network